/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Index3RouteImport } from './routes/index3'
import { Route as IndexRouteImport } from './routes/index'

const Index3Route = Index3RouteImport.update({
  id: '/index3',
  path: '/index3',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index3': typeof Index3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index3': typeof Index3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/index3': typeof Index3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index3'
  id: '__root__' | '/' | '/index3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Index3Route: typeof Index3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index3': {
      id: '/index3'
      path: '/index3'
      fullPath: '/index3'
      preLoaderRoute: typeof Index3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Index3Route: Index3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
